# Generated by Django 5.2.15 on 2026-06-20 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('sop_code', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='sops/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sop_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SOPChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=180)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sops.sopdocument')),
            ],
        ),
    ]
