# Generated by Django 5.2.15 on 2026-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopchunk',
            name='chunking_strategy',
            field=models.CharField(blank=True, choices=[('heading', 'Heading-aware'), ('semantic', 'Semantic (embeddings)'), ('fixed_length', 'Fixed-length')], max_length=20, null=True),
        ),
    ]
