# Generated by Django 5.2.15 on 2026-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_topicmastery_elo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmastery',
            name='fsrs_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='fsrs_stability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
