# Generated by Django 5.2.15 on 2026-08-04 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_role_groups'),
        ('attempts', '0004_topicmastery_fsrs_difficulty_and_more'),
        ('sops', '0002_sopchunk_chunking_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_index', models.PositiveSmallIntegerField(default=0)),
                ('streak_correct', models.PositiveSmallIntegerField(default=0)),
                ('mastery_status', models.CharField(choices=[('in_progress', 'In Progress'), ('mastered', 'Mastered')], default='in_progress', max_length=20)),
                ('next_eligible_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('elo_rating', models.FloatField(default=1500)),
                ('fsrs_stability', models.FloatField(blank=True, null=True)),
                ('fsrs_difficulty', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobrole')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_masteries', to=settings.AUTH_USER_MODEL)),
                ('sop_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='sops.sopchunk')),
            ],
            options={
                'ordering': ['next_eligible_at'],
                'unique_together': {('learner', 'sop_chunk')},
            },
        ),
    ]
