# Generated by Django 5.2.15 on 2026-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0007_backfill_offered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='learner_ability_at_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question_difficulty_at_answer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
