# Generated by Django 5.2.15 on 2026-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0008_attemptanswer_learner_ability_at_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
