# Generated by Django 5.2.15 on 2026-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
