# Generated by Django 5.2.15 on 2026-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='generation_source',
            field=models.CharField(blank=True, choices=[('nvidia_nim', 'NVIDIA NIM'), ('mock', 'Offline fallback'), ('manual', 'Manually authored')], max_length=20, null=True),
        ),
    ]
