# Generated by Django 5.2.15 on 2026-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_generation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='elo_rating',
            field=models.FloatField(default=1500),
        ),
    ]
