# Generated by Django 5.2.15 on 2026-07-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('sop_uploaded', 'SOP Uploaded'), ('sop_processed', 'SOP Processed'), ('sop_process_failed', 'SOP Processing Failed'), ('questions_generated', 'Questions Generated'), ('question_approved', 'Question Approved'), ('question_rejected', 'Question Rejected'), ('quiz_attempt_submitted', 'Quiz Attempt Submitted'), ('sop_chat_query', 'SOP Chat Query'), ('quiz_attempt_auto_assigned', 'Quiz Attempt Auto-Assigned')], max_length=40),
        ),
    ]
